version: '3'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
    - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    links:
    - mysql
    depends_on:
    - mysql
    networks:
    - keycloak-network
  mysql:
    container_name: mysql
    image: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
          - ./mysql:/var/lib/mysql
    networks:
    - keycloak-network
networks:
  keycloak-network:
