version: '2'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:3.4.3.Final
    ports:
    - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    links:
    - mysql
    - maildev
    depends_on:
    - mysql
    - maildev
    networks:
    - keycloak-network
    volumes:
    - ./providers:/opt/jboss/keycloak/providers
    - ./shared:/shared
    entrypoint:
    - "/shared/custom-docker-entrypoint.sh"
  mysql:
    container_name: mysql
    image: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
          - ./mysql:/var/lib/mysql
    networks:
    - keycloak-network
  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    ports:
      - "8081:80"
    networks:
    - keycloak-network
networks:
  keycloak-network:
